/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Aman Sariyev
 */
public class FsmGui extends javax.swing.JPanel {

	/**
	 * Creates new form FsmGui
	 */
	public FsmGui() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		aut = new Automaton();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();

		setLayout(new java.awt.GridBagLayout());

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 0, Short.MAX_VALUE)
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 0, Short.MAX_VALUE)
		);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridheight = 10;
		add(jPanel1, gridBagConstraints);

		jLabel1.setText("Import from File");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 3;
		add(jLabel1, gridBagConstraints);

		jLabel2.setText("Regular Expression");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 3;
		add(jLabel2, gridBagConstraints);

		jLabel3.setText("Automaton");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = 3;
		add(jLabel3, gridBagConstraints);

		jLabel4.setText("Conversion");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.gridwidth = 3;
		add(jLabel4, gridBagConstraints);

		jLabel5.setText("Check acceptance");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 8;
		gridBagConstraints.gridwidth = 3;
		add(jLabel5, gridBagConstraints);

		jTextField1.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridwidth = 3;
		add(jTextField1, gridBagConstraints);

		jTextField2.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 9;
		gridBagConstraints.gridwidth = 3;
		add(jTextField2, gridBagConstraints);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(20);
		jScrollPane1.setViewportView(jTextArea1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.gridwidth = 3;
		add(jScrollPane1, gridBagConstraints);

		jButton1.setText("RegExp");
		jButton1.addActionListener(this::jButton1ActionPerformed);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		add(jButton1, gridBagConstraints);

		jButton2.setText("Automaton");
		jButton2.addActionListener(this::jButton2ActionPerformed);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		add(jButton2, gridBagConstraints);

		jButton3.setText("Create");
		jButton3.addActionListener(this::jButton3ActionPerformed);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 3;
		add(jButton3, gridBagConstraints);

		jButton4.setText("Create");
		jButton4.addActionListener(this::jButton4ActionPerformed);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 5;
		add(jButton4, gridBagConstraints);

		jButton5.setText("To DFA");
		jButton5.addActionListener(this::jButton5ActionPerformed);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 7;
		gridBagConstraints.gridwidth = 2;
		add(jButton5, gridBagConstraints);

		jButton6.setText("To RegExp");
		jButton6.addActionListener(this::jButton6ActionPerformed);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 7;
		add(jButton6, gridBagConstraints);

		jButton7.setText("Check");
		jButton7.addActionListener(this::jButton7ActionPerformed);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 9;
		add(jButton7, gridBagConstraints);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		JFileChooser jFileChooser = new JFileChooser();
		jFileChooser.setCurrentDirectory(new File("."));
		jFileChooser.setDialogTitle("Select File with Regular Expression");
		int returnVal = jFileChooser.showOpenDialog(FsmGui.this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file = jFileChooser.getSelectedFile();
			List<String> lines = new ArrayList<>();
			try (BufferedReader br = new BufferedReader(new FileReader(file.getPath()))) {
				String sCurrentLine;
				while ((sCurrentLine = br.readLine()) != null) {
					lines.add(sCurrentLine);
				}
				if (lines.size() == 0) throw new Exception("File is empty");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
				return;
			}
			if (lines.size() > 1) JOptionPane.showMessageDialog(null, "Too many lines, only first taken");
			jTextField1.setText(lines.get(0));
		}
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		JFileChooser jFileChooser = new JFileChooser();
		jFileChooser.setCurrentDirectory(new File("."));
		jFileChooser.setDialogTitle("Select File with Automaton");
		int returnVal = jFileChooser.showOpenDialog(FsmGui.this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file = jFileChooser.getSelectedFile();
			List<String> lines = new ArrayList<>();
			try (BufferedReader br = new BufferedReader(new FileReader(file.getPath()))) {
				String sCurrentLine;
				while ((sCurrentLine = br.readLine()) != null) {
					lines.add(sCurrentLine);
				}
				if (lines.size() == 0) throw new Exception("File is empty");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
				return;
			}
			jTextArea1.setText((String.join("\n", lines)));
		}
	}//GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		aut = AutomatonUtils.convertRegExpToAutomaton(jTextField1.getText());
		jTextArea1.setText(aut.toString());
	}//GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jButton4ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		aut = AutomatonUtils.simplifyAutomaton(aut);
		jTextArea1.setText(aut.toString());
	}//GEN-LAST:event_jButton5ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
		jTextField1.setText(AutomatonUtils.convertAutomatonToRegExp(aut));
	}//GEN-LAST:event_jButton6ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
		try {
			jTextField2.setText(AutomatonUtils.checkAcceptability(aut, jTextField2.getText()) ? "YES" : "NO");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e);
		}
	}//GEN-LAST:event_jButton7ActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables
	private Automaton aut;
}
